### ISSUE TITLE
Known implementations

### ISSUE THREAD

**Issue by muliyul** [bozaro/git-lfs-java#101]
Is there a section with known implementations for this? (`*Manager` classes?)

**Comment by slonopotamus** [comment]
Yep, see https://github.com/bozaro/git-as-svn/tree/master/src/main/kotlin/svnserver/ext/gitlfs/server

**Comment by muliyul** [comment]
I want to use this for s3 storage but not sure how to go about this.

**Comment by muliyul** [comment]
@slonopotamus What is the object hash I need to pass to the client in order to download a blob? Is it the hash of the content? hash of the commit?

**Comment by slonopotamus** [comment]
It's the hash of LFS object from [pointer file](https://github.com/git-lfs/git-lfs/blob/main/docs/spec.md#the-pointer).

So if you have, for example, this file:
```
version https://git-lfs.github.com/spec/v1
oid sha256:4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393
size 12345
```

Then hash is `4d7a214614ab2935c943f9e0ff69d22eadbb8f32b1258daaa5e2ca24d17e2393`.

You can use `ru.bozaro.gitlfs.pointer.Pointer#parsePointer` and `ru.bozaro.gitlfs.pointer.Pointer#serializePointer` to save/load pointer files.

So, the whole procedure is something like this:

```kotlin
val OID_PREFIX = "sha256:"

val bytes = ...; // Read pointer file from somewhere
val lfsClient = ...; // Construct client

val pointer = Pointer.parsePointer(bytes, 0, length)!!
val oid = pointer[Constants.OID]
val size = pointer[Constants.SIZE].toLong()
val hash: String = oid.substring(LfsStorage.OID_PREFIX.length)

val dataStream = lfsClient.openObject(hash)
```
