### ISSUE TITLE
JFrog Artifactory git-lfs compatibility

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-lfs-java#4]
See https://github.com/bozaro/git-lfs-migrate/issues/23

**Comment by bozaro** [comment]
JFrog Artifactory 4.15.0 has incorrect Git LFS server implementation.

## Batch API issues
https://github.com/git-lfs/git-lfs/blob/aceb2d22293cecf9788f7807f52acd0ad5b72f0f/docs/api/README.md

### Invalid `actions` property name
`objects/batch` response uses `_links` property instead of `actions`.
For example:
```
{
  "objects" : [ {
    "oid" : "b810bbe954d51e380f395de0c301a0a42d16f115453f2feb4188ca9f7189074e",
    "size" : 28,
    "_links" : {
      "upload" : {
        "href" : "http://localhost:8081/artifactory/jfrog-lfs/objects/b8/10/b810bbe954d51e380f395de0c301a0a42d16f115453f2feb4188ca9f7189074e;sha256=b810bbe954d51e380f395de0c301a0a42d16f115453f2feb4188ca9f7189074e",
        "header" : {
        }
      }
    }
  } ]
}
```
Instead of:
```
{
  "objects" : [ {
    "oid" : "b810bbe954d51e380f395de0c301a0a42d16f115453f2feb4188ca9f7189074e",
    "size" : 28,
    "actions" : {
      "upload" : {
        "href" : "http://localhost:8081/artifactory/jfrog-lfs/objects/b8/10/b810bbe954d51e380f395de0c301a0a42d16f115453f2feb4188ca9f7189074e;sha256=b810bbe954d51e380f395de0c301a0a42d16f115453f2feb4188ca9f7189074e",
        "header" : {
        }
      }
    }
  } ]
}
```

If client don't recognise `_links` property, it will recognise object as already uploaded.

### Incorrect request for already uploaded object

> If a client requests to upload an object that the server already has, the server should omit the actions property completely.

Actifactory `objects/batch` response always send "upload" links for already uploaded objests, but by specification the server should omit the actions property completely.

**Comment by bozaro** [comment]
## Basic transref issues
https://github.com/git-lfs/git-lfs/blob/aceb2d22293cecf9788f7807f52acd0ad5b72f0f/docs/api/basic-transfers.md

### Invalid HTTP status code for created objects
PUT response has status code 201 for created objects instead of 200.

### Invalid HTTP status code for already uploaded objects
> A 200 response means that the object exists on the server.

PUT response has status code 403 for already uploaded objects instead of 200.

For example:
```
HTTP/1.1 403 Forbidden
Server: Artifactory/4.15.0
X-Artifactory-Id: 3e5d8ffe0d057e8a:-1ff10f82:15905fdf100:-8000
Content-Type: application/json;charset=ISO-8859-1
Date: Fri, 16 Dec 2016 05:21:16 GMT

{
  "errors" : [ {
    "status" : 403,
    "message" : "Not enough permissions to overwrite artifact 'jfrog-lfs:objects/2c/26/2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae' (user 'test' needs DELETE permission)."
  } ]
}
```

**Comment by bozaro** [comment]
JFrog ticket: 52635

**Comment by bozaro** [comment]
Related tickets:
https://www.jfrog.com/jira/browse/RTFACT-12947
https://www.jfrog.com/jira/browse/RTFACT-12951

**Comment by slonopotamus** [comment]
Both Artifactory issues were fixed back in 2017.
